### ISSUE TITLE
[bug] The number of votes differs from the actual number.

### ISSUE THREAD

**Issue by LGSYukiSugiyama** [cosmos-gaminghub/explorer-frontend#66]
## Summary of Bug
1, The number of votes differs from the actual number.
Each total number of Proposition 1 of Nibiru-2000 is different.
The correct number for "No" is 346989.501865.
The correct number for "No With Veto" is 10.000000.
Therefore, the Total GAME will be different.
https://nibiru-2000.game-explorer.io/proposals/1
![test](https://user-images.githubusercontent.com/89244937/133610360-75b557aa-72ad-40df-b93c-898c76a43dad.png)

2, The voter figures are different.
When a voter changes a voting item, the number of votes is increased while the voting item before the change remains.
The image is just an example.
In this image, two of the same delegator addresses exist and are accounted for.
The same phenomenon occurs for "yes", "No", "No with veto", and "Abstain".
![test2](https://user-images.githubusercontent.com/89244937/133611163-d3d3347a-fd44-4cb4-8ccd-2d1135aa4b63.png)

## Version
latest master(d28f664)

## Steps to Reproduce

1, The number of votes differs from the actual number.
You can check the correct values in the following query execution result.
```
# nibirud q gov tally 1 --chain-id=nibiru-2000
abstain: "124419000010"
"no": "346989501865"
no_with_veto: "10000000"
"yes": "244073001000"
```
2, The voter figures are different.
You can see the status of each voter in the following query results.
According to this, the number of "ALL" is 9.
The number of "yes" and "no" is 3.
There is one "No With Veto".
"Abstain" is 2 people.
I think it would be easier to understand if the explorer displayed the results like this.
```
# nibirud q gov votes 1
pagination:
  next_key: null
  total: "0"
votes:
- option: VOTE_OPTION_YES
  proposal_id: "1"
  voter: nibiru1qmhuaq0f78q93k58ma8jmq65dzx2n889w7mhg6
- option: VOTE_OPTION_NO
  proposal_id: "1"
  voter: nibiru1pzs7dnhp9n0yaulr6hvdwhav6my55lk082mcgx
- option: VOTE_OPTION_NO
  proposal_id: "1"
  voter: nibiru1pyf0djx0sevym42y8gyvum3l7rdxj9ql0md4u5
- option: VOTE_OPTION_ABSTAIN
  proposal_id: "1"
  voter: nibiru1z9u3cftn89jdqpfm8993r4z7d398auc7tajkgf
- option: VOTE_OPTION_YES
  proposal_id: "1"
  voter: nibiru19sw98d9uvaqwhd4hgdu5mzpes7zfx3vr3lgw5d
- option: VOTE_OPTION_ABSTAIN
  proposal_id: "1"
  voter: nibiru195ua2gnseuv3d5jtwypujef0feym05devxkak6
- option: VOTE_OPTION_YES
  proposal_id: "1"
  voter: nibiru1uqfal9sqazj3w6h8kcezkymwt0p22nyrffc3m0
- option: VOTE_OPTION_NO_WITH_VETO
  proposal_id: "1"
  voter: nibiru1u5spl60f9y9cj0z8r69lvcesu74a3ct9qfcd85
- option: VOTE_OPTION_NO
  proposal_id: "1"
  voter: nibiru1l94c5al6t3ak9yx6zxwsrxnfy9d5dgupq8qq95
```

____
